# This file is a template, and might need editing before it works on your project.
---

variables:
  MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true -s $CI_PROJECT_DIR/.mvn/local-settings.xml"

  SONAR_TOKEN: "7f0a8427f9667ae14a3c75984a41d288122d6191"
  SONAR_HOST_URL: "http://192.168.1.102:9000"
  SONAR_USER_HOME: /home/scanner-cli/
  GIT_DEPTH: 0
  
# Cache downloaded dependencies and plugins between builds.
# To keep cache across branches add 'key: "$CI_JOB_NAME"'
cache:
  paths:
    - .m2/repository

stages:
  - test
  - sonarqube
  - package
  - buildAndPushImage

# This will only validate and compile stuff and run e.g. maven-enforcer-plugin.
# Because some enforcer rules might check dependency convergence and class duplications
# we use `test-compile` here instead of `validate`, so the correct classpath is picked up.
.validate: &validate
  stage: test
  script:
    - 'mvn $MAVEN_CLI_OPTS test-compile'

sonarqube-check:
  stage: sonarqube
  image: maven:3.3.9-jdk-8
  script:
    - 'mvn $MAVEN_CLI_OPTS verify sonar:sonar -Dsonar.qualitygate.wait=true'
  allow_failure: true
  only:
    - merge_requests
    - master

# Validate merge requests using JDK8
validate:jdk8:
  <<: *validate
  image: maven:3.3.9-jdk-8
  
package:
  stage: package
  script:
    - 'mvn $MAVEN_CLI_OPTS package'
  image: maven:3.3.9-jdk-8
  artifacts:
    paths:
      - target/*.jar

before_script:
  - export DOCKER_HOST="tcp://192.168.1.129:2375"

build:
  stage: buildAndPushImage
  script:
    - echo $CI_PROJECT_NAME
    - "name=$( echo $CI_PROJECT_NAME | tr A-Z a-z )"
    - docker info
    - docker build $CI_PROJECT_DIR -t 192.168.1.102:5000/3s/$name:last_ci
    - docker login 192.168.1.102:5000 -u 'robot$harbor_robot' -p '8ZpPV3xg28jxj6Sz4ZUEIM2zfdqabF2g'
    - docker push 192.168.1.102:5000/3s/$name:last_ci
  image: docker:git
